import { Admin, User, Course, Invoice, Learner } from "@/types/types";

const admins: Admin[] = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        email: "john.doe@example.com",
        password: "password123",
        contact: "123-456-7890",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        email: "jane.smith@example.com",
        password: "password123",
        contact: "098-765-4321",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

const users: User[] = [
    {
        id: 1,
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice.johnson@example.com",
        password: "password123",
        contact: "111-222-3333",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        firstName: "Bob",
        lastName: "Brown",
        email: "bob.brown@example.com",
        password: "password123",
        contact: "444-555-6666",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

const courses: Course[] = [
    {
        id: 1,
        title: "Introduction to Programming",
        price: 99.99,
        duration: "4 weeks",
        instructor: "Dr. Smith",
        learners: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        title: "Advanced JavaScript",
        price: 149.99,
        duration: "6 weeks",
        instructor: "Prof. Johnson",
        learners: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

const invoices: Invoice[] = [
    {
        id: 1,
        learner: "Alice Johnson",
        email: "alice.johnson@example.com",
        amount: 99.99,
        date: new Date(),
        status: "Paid",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        learner: "Bob Brown",
        email: "bob.brown@example.com",
        amount: 149.99,
        date: new Date(),
        status: "Pending",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
const learners: Learner[] = [
    {
        id: 1,
        firstName: "Charlie",
        lastName: "Williams",
        email: "charlie.williams1@example.com",
        program: "Computer Science",
        gender: "Male",
        location: "New York",
        phone: "777-888-9991",
        disabled: false,
        amount: 200.00,
        image: "https://github.com/shadcn.png",
        description: "A dedicated learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        firstName: "Diana",
        lastName: "Evans",
        email: "diana.evans1@example.com",
        program: "Data Science",
        gender: "Female",
        location: "San Francisco",
        phone: "000-111-2221",
        disabled: false,
        amount: 250.00,
        image: "https://github.com/shadcn.png",
        description: "An enthusiastic learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        firstName: "Ethan",
        lastName: "Harris",
        email: "ethan.harris@example.com",
        program: "Software Engineering",
        gender: "Male",
        location: "Los Angeles",
        phone: "333-444-5555",
        disabled: false,
        amount: 300.00,
        image: "https://github.com/shadcn.png",
        description: "A passionate learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        firstName: "Fiona",
        lastName: "Clark",
        email: "fiona.clark@example.com",
        program: "Cyber Security",
        gender: "Female",
        location: "Chicago",
        phone: "666-777-8888",
        disabled: false,
        amount: 350.00,
        image: "https://github.com/shadcn.png",
        description: "A motivated learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        firstName: "George",
        lastName: "Martinez",
        email: "george.martinez@example.com",
        program: "Artificial Intelligence",
        gender: "Male",
        location: "Houston",
        phone: "999-000-1111",
        disabled: false,
        amount: 400.00,
        image: "https://github.com/shadcn.png",
        description: "An innovative learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        firstName: "Hannah",
        lastName: "Walker",
        email: "hannah.walker@example.com",
        program: "Machine Learning",
        gender: "Female",
        location: "Phoenix",
        phone: "222-333-4444",
        disabled: false,
        amount: 450.00,
        image: "https://github.com/shadcn.png",
        description: "A curious learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        firstName: "Ian",
        lastName: "Robinson",
        email: "ian.robinson@example.com",
        program: "Data Analytics",
        gender: "Male",
        location: "Philadelphia",
        phone: "555-666-7777",
        disabled: false,
        amount: 500.00,
        image: "https://github.com/shadcn.png",
        description: "A detail-oriented learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        firstName: "Julia",
        lastName: "Lewis",
        email: "julia.lewis@example.com",
        program: "Blockchain Technology",
        gender: "Female",
        location: "San Antonio",
        phone: "888-999-0000",
        disabled: false,
        amount: 550.00,
        image: "https://github.com/shadcn.png",
        description: "A forward-thinking learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        firstName: "Kevin",
        lastName: "Young",
        email: "kevin.young@example.com",
        program: "Cloud Computing",
        gender: "Male",
        location: "San Diego",
        phone: "111-222-3333",
        disabled: false,
        amount: 600.00,
        image: "https://github.com/shadcn.png",
        description: "A tech-savvy learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        firstName: "Laura",
        lastName: "King",
        email: "laura.king@example.com",
        program: "Internet of Things",
        gender: "Female",
        location: "Dallas",
        phone: "444-555-6666",
        disabled: false,
        amount: 650.00,
        image: "https://github.com/shadcn.png",
        description: "An innovative learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        firstName: "Michael",
        lastName: "Scott",
        email: "michael.scott@example.com",
        program: "Robotics",
        gender: "Male",
        location: "Austin",
        phone: "777-888-9999",
        disabled: false,
        amount: 700.00,
        image: "https://github.com/shadcn.png",
        description: "A creative learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        firstName: "Nina",
        lastName: "Adams",
        email: "nina.adams@example.com",
        program: "Virtual Reality",
        gender: "Female",
        location: "Jacksonville",
        phone: "000-111-2222",
        disabled: false,
        amount: 750.00,
        image: "https://github.com/shadcn.png",
        description: "An imaginative learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 13,
        firstName: "Oliver",
        lastName: "Baker",
        email: "oliver.baker@example.com",
        program: "Augmented Reality",
        gender: "Male",
        location: "Fort Worth",
        phone: "333-444-5555",
        disabled: false,
        amount: 800.00,
        image: "https://github.com/shadcn.png",
        description: "A visionary learner",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export { admins, users, courses, invoices, learners };